Controller FW: Add support for python-hid 1.0.6+
Since the release of python-hid 1.0.6, there is a new Enum type called
`BusType`. That class cannot be serialized with JSON, resulting in the
following error:
```
Traceback (most recent call last):
File "/usr/share/jupiter_controller_fw_updater/d21bootloader16.py", line
1220, in <module>
  cli()
File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in
__call__
  return self.main(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in
main
  rv = self.invoke(ctx)
       ^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/click/core.py", line 1688, in
invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in
invoke
  return ctx.invoke(self.callback, **ctx.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in
invoke
  return __callback(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/jupiter_controller_fw_updater/d21bootloader16.py", line
1074, in get_devices_json
  print(json.dumps(devs))
        ^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/json/__init__.py", line 231, in dumps
  return _default_encoder.encode(obj)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/json/encoder.py", line 200, in encode
  chunks = self.iterencode(o, _one_shot=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/json/encoder.py", line 258, in iterencode
  return _iterencode(o, 0)
         ^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/json/encoder.py", line 180, in default
  raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BusType is not JSON serializable
```

With this commit we cast the Enum to an int, to allow JSON to serialize
its value.

This effectively bumps the minimum python-hid dependency to be 1.0.6+.

Signed-off-by: Ludovico de Nittis <ludovico.denittis@collabora.com>