format-device: unmount filesystems on device before repartition/format
If format-device is called on a disk with mounted filesystems, then it
can fail later since the kernel is still using the old partition info:

    Error: Partition(s) 1 on /dev/mmcblk0 have been written, but we have
    been unable to inform the kernel of the change, probably because
    it/they are in use.  As a result, the old partition(s) will remain
    in use.  You should reboot now before making further changes.

This avoids that situation by umounting all mountpoints associated with
the given disk *before* any changes are made to the disk

errno 32 is returned, which is what umount will return if the mount
point is in use. This seems (in my experience) to be a common reason why
umount would fail, and it's a unique ret val in the script (nothing else
explicitly causes the script to return 32)